
name: test-teamcity-server

services:
  postgres:
    # https://hub.docker.com/_/postgres
    container_name: test-teamcity-server-db
    image: postgres:16.4
    restart: always
    volumes:
      - "test-teamcity-server-postgres:/var/lib/postgresql/data"
      - "test-teamcity-server-postgres-backups:/backups"
      - "${PWD}/postgres/etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "${PWD}/postgres/docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TEAMCITY_DB_PASSWORD: "${TEAMCITY_DB_PASSWORD}"
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en-US"
      LANG: "en_US.UTF-8"
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: test-teamcity-server-pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - "test-teamcity-server-pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres

  teamcity:
    container_name: test-teamcity-server
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    restart: always
    ports:
      - "${TEAMCITY_HTTP_PORT}:8111"
      - "${TEAMCITY_HTTPS_PORT}:443"
    volumes:
      # https://www.jetbrains.com/help/teamcity/teamcity-data-directory.html#Structure+of+TeamCity+Data+Directory
      - "test-teamcity-server-data:/data/teamcity_server/datadir"
      - "test-teamcity-server-logs:/opt/teamcity/logs"
    environment:
      # https://www.jetbrains.com/help/teamcity/set-up-external-database.html#Properties+File
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx4g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=640m"
      TEAMCITY_DB_URL: "jdbc:postgresql://postgres:5432/teamcity"
      TEAMCITY_DB_USER: "teamcity"
      TEAMCITY_DB_PASSWORD: "${TEAMCITY_DB_PASSWORD}"
      SERVER_URL: "${SERVER_URL}"
    depends_on:
      - postgres

  teamcity-agent-1:
    container_name: test-teamcity-agent-1
    restart: always
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - test-teamcity-agent-1:/data/teamcity_agent
    environment:
      DOCKER_IN_DOCKER: "start"
      SERVER_URL: "http://teamcity:8111"
      AGENT_NAME: "agent1"
    depends_on:
      - teamcity

volumes:
  test-teamcity-server-data:
  test-teamcity-server-logs:
  test-teamcity-server-postgres:
  test-teamcity-server-postgres-backups:
  test-teamcity-server-pgadmin:
  test-teamcity-agent-1:
